### ISSUE TITLE
Need to code Navbar Dropdown

### ISSUE THREAD

**Issue by Jake7500** [Jake7500/4151643034#4]
Navbar Dropdown needs coding.

**Comment by xIdyllic** [comment]
Dropdown has been coded. Issues with positioning - something I'm really bad at. Need you to take a look Jake.

**Comment by Jake7500** [comment]
Recoded dropdown and is 99% Fixed apart from a minor alignment issue with the dropdown toggle.

**Comment by Jake7500** [comment]
Recoded navbar dropdown with a new one, is 99% working but needs minor alignment issues but we will call it fixed.
